# Generated by Django 5.0.6 on 2024-05-20 20:23

import django.db.models.deletion
import movies.api.tmdb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("poster_path", models.CharField(max_length=255)),
                ("backdrop_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("imdb_id", models.CharField(max_length=255)),
                ("adult", models.BooleanField()),
                ("backdrop_path", models.CharField(max_length=255)),
                ("budget", models.IntegerField()),
                ("homepage", models.CharField(max_length=255)),
                ("origin_country", models.CharField(max_length=255)),
                ("original_language", models.CharField(max_length=255)),
                ("original_title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("popularity", models.FloatField()),
                ("poster_path", models.CharField(max_length=255)),
                ("production_companies", models.CharField(max_length=255)),
                ("production_countries", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("revenue", models.IntegerField()),
                ("runtime", models.IntegerField()),
                ("spoken_languages", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("tagline", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("video", models.BooleanField()),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.collection",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.genre"
                    ),
                ),
            ],
            bases=(movies.api.tmdb.TMDBAPIMixin, models.Model),
        ),
    ]
