# Generated by Django 5.0.6 on 2024-05-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField()),
                ("secure_base_url", models.URLField()),
                ("backdrop_sizes", models.CharField(max_length=200)),
                ("logo_sizes", models.CharField(max_length=200)),
                ("poster_sizes", models.CharField(max_length=200)),
                ("profile_sizes", models.CharField(max_length=200)),
                ("still_sizes", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("original_title", models.CharField(max_length=200)),
                ("overview", models.TextField()),
                ("release_date", models.DateField()),
                ("runtime", models.IntegerField()),
                ("revenue", models.IntegerField()),
                ("budget", models.IntegerField()),
                ("genres", models.CharField(max_length=200)),
                ("languages", models.CharField(max_length=200)),
                ("production_companies", models.CharField(max_length=200)),
                ("production_countries", models.CharField(max_length=200)),
                ("spoken_languages", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=50)),
                ("tagline", models.CharField(max_length=200)),
                ("video", models.BooleanField()),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crew_id", models.IntegerField()),
                ("job", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.IntegerField()),
                ("character_name", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
        ),
    ]
