# Generated by Django 5.0.6 on 2024-05-18 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crew",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="images",
        ),
        migrations.DeleteModel(
            name="Cast",
        ),
        migrations.DeleteModel(
            name="Crew",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
