# Generated by Django 5.0.6 on 2024-05-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("iso_639_1", models.CharField(max_length=10)),
                ("english_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo_path", models.CharField(max_length=255)),
                ("origin_country", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("iso_3166_1", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="production_companies",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="production_countries",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="spoken_languages",
        ),
        migrations.AddField(
            model_name="movie",
            name="spoken_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.language",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.productcompany",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.productcountry",
            ),
        ),
    ]
